services:
  postgres:
    image: postgres:16
    container_name: dartreplay-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: dartreplay
      POSTGRES_USER: dartreplay
      POSTGRES_PASSWORD: dartreplay123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
